<?php if(($_GET['erro']??'')==='sem_permissao'): ?><div class="courier-alert">🔒 O dono definiu que somente o caixa fecha comandas.</div><?php endif; ?>
<div class="mhead waiter-head"><div class="mh"><a href="?r=waiter" class="back">←</a><div class="lg">🧾</div><div><h2>Mesa <?= e($mesa) ?></h2><div class="meta">Atendente: <?= e($garcom) ?></div></div></div></div>
<main class="waiter-order">
  <section class="command-card"><h3>Comanda atual</h3><div id="comanda">
    <?php if(!$itens): ?><p class="command-empty">Nenhum item. Toque nos produtos abaixo para adicionar.</p><?php endif; ?>
    <?php foreach($itens as $it): ?><div class="command-item"><div><strong><?= (int)$it['qtd'] ?>×</strong><span><?= e($it['nome']) ?></span></div><div><b><?= money($it['qtd']*$it['preco']) ?></b><button aria-label="Remover um item" onclick="rem(<?= $it['id'] ?>)">−</button></div></div><?php endforeach; ?>
  </div><div class="command-total"><span>Total</span><b><?= money($ord['total']??0) ?></b></div><?php if($itens && ($ord['status']??'')==='mesa_rascunho'): ?><button class="generate-order" onclick="gerarPedido()">GERAR PEDIDO E OCUPAR MESA</button><?php elseif($itens && !empty($podeFechar)): ?><button class="close-bill" onclick="document.getElementById('payModal').classList.add('on')">💳 Fechar conta e receber</button><?php elseif($itens): ?><div class="no-close">🔒 O fechamento desta comanda é feito pelo <b>caixa</b>. Leve o cliente ao caixa ou avise o operador.</div><?php endif; ?></section>
  <h3 class="add-title">Adicionar itens</h3><div class="chips waiter-chips"><button class="chip on" onclick="filtC('all',this)">Todos</button><?php foreach($cats as $c): ?><button class="chip" onclick="filtC('c<?= $c['id'] ?>',this)"><?= e($c['nome']) ?></button><?php endforeach; ?></div>
  <div class="wprods"><?php foreach($prods as $p): ?><button class="wprod c<?= $p['category_id'] ?>" onclick="add(<?= $p['id'] ?>)"><span class="wp-emoji"><?php if(!empty($p['foto'])): ?><img src="<?= e($p['foto']) ?>" alt=""><?php else: ?><?= e($p['emoji']) ?><?php endif; ?></span><span class="wp-nome"><?= e($p['nome']) ?></span><span class="wp-preco"><?= money($p['preco']) ?></span></button><?php endforeach; ?></div>
</main>
<div class="pay-modal" id="payModal"><form method="post" action="?r=waiter_fechar" class="pay-dialog" onsubmit="return confirm('Confirmar recebimento e fechar a Mesa <?= e($mesa) ?>?')"><button type="button" class="x" onclick="payModal.classList.remove('on')">×</button><h3>Receber <?= money($ord['total']??0) ?></h3><p>Escolha como o cliente pagou. Vai ficar registrado que <b><?= e($garcom) ?></b> fechou e recebeu esta comanda.</p><div class="waiter-pay"><label><input type="radio" name="metodo" value="debito" required><span>💳<b>Débito</b></span></label><label><input type="radio" name="metodo" value="credito"><span>💳<b>Crédito</b></span></label><label><input type="radio" name="metodo" value="pix"><span>◆<b>Pix</b></span></label><label><input type="radio" name="metodo" value="dinheiro"><span>💵<b>Dinheiro</b></span></label></div><input type="hidden" name="mesa" value="<?= e($mesa) ?>"><button class="confirm-pay">Confirmar pagamento e fechar</button></form></div>
<script>
const MESA='<?= e($mesa) ?>';
async function add(pid){const r=await fetch('?r=waiter_add',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'mesa='+encodeURIComponent(MESA)+'&product_id='+pid}).then(x=>x.json());if(r.ok)location.reload()}
async function rem(iid){if(!confirm('Remover uma unidade deste item?'))return;await fetch('?r=waiter_remove',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'item_id='+iid+'&mesa='+encodeURIComponent(MESA)});location.reload()}
async function gerarPedido(){const r=await fetch('?r=waiter_generate',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:'mesa='+encodeURIComponent(MESA)}).then(x=>x.json());if(r.ok){alert('Pedido gerado e enviado à cozinha. A mesa está ocupada.');location.reload()}else alert('Não foi possível gerar o pedido.')}
function filtC(cls,el){document.querySelectorAll('.waiter-chips .chip').forEach(c=>c.classList.remove('on'));el.classList.add('on');document.querySelectorAll('.wprod').forEach(p=>p.style.display=(cls==='all'||p.classList.contains(cls))?'flex':'none')}
</script>
